---
- hosts: leihs.local
  roles:
    - { role: leihs-instance,
        server_name: "leihs.local",
        deploy_to: "/home/leihs/test/current",
        version: "master",
        document_root: "/home/leihs/test/current/public",
        passenger_ruby: "/home/leihs/.rbenv/versions/2.1.5/bin/ruby",
        user: leihs,
        authorized_for_deployment:
          ["files/ssh_keys/rca.pub",
           "files/ssh_keys/fs.pub",
           "files/ssh_keys/nimaai.pub"],
        mysql_user: leihs,
        mysql_password: "hNM8f7ej2sjjnlk02hd",
        mysql_database: "leihs_prod",
        secret_token: fdb800e432b92b5421209ce179506b563e176d5ad6b309a3dd6c882c0563f60b206a4eeab26ada269ad3b7c5ca4d357611d387fe13a8572964123ea16cfe9d0a,
        rotate_logs: "/home/leihs/test/shared/log/*.log",
        test_instance: True
        }

# An example with MySQL database hosted on a secondary server and accessed via TCP
- hosts: leihs2.local
  roles:
    - { role: leihs-instance,
        server_name: "leihs2.local",
        deploy_to: "/home/leihs2/test/current",
        version: "master",
        document_root: "/home/leihs2/test/current/public",
        passenger_ruby: "/home/leihs2/.rbenv/versions/2.1.5/bin/ruby",
        user: leihs2,
        authorized_for_deployment:
          ["files/ssh_keys/rca.pub"],
        mysql_user: leihs,
        mysql_password: "r3yjqWkzYXjU.",
        mysql_database: "leihs_prod",
        mysql_host: "192.168.122.235",
        local_database: False,
        secret_token: fdb800e432b92b5421209ce179506b563e176d5ad6b309a3dd6c882c0563f60b206a4eeab26ada269ad3b7c5ca4d357611d387fe13a8572964123ea16cfe9d0a,
        rotate_logs: "/home/leihs/test/shared/log/*.log",
        test_instance: True
        }
