---
- hosts: leihs.local
  roles:
    - { role: leihs-instance,
        deploy_to: "/home/leihs/test",
        version: "master",
        ruby_version: "2.1.5",
        user: leihs,
        authorized_for_deployment:
          ["files/ssh_keys/rca.pub",
           "files/ssh_keys/fs.pub",
           "files/ssh_keys/nimaai.pub"],
        mysql_user: leihs,
        mysql_password: "hNM8f7ej2sjjnlk02hd",
        mysql_database: "leihs_prod",
        secret_token: fdb800e432b92b5421209ce179506b563e176d5ad6b309a3dd6c882c0563f60b206a4eeab26ada269ad3b7c5ca4d357611d387fe13a8572964123ea16cfe9d0a,
        logrotate_filename: "leihs.local",
        test_instance: True
        }
    - { role: phusion-passenger-vhost,
        server_name: "leihs.local" }

# An example with MySQL database hosted on a secondary server and accessed via TCP
- hosts: leihs2.local
  roles:
    - { role: leihs-instance,
        deploy_to: "/home/leihs2/test",
        version: "master",
        ruby_version: "2.1.5",
        user: leihs2,
        authorized_for_deployment:
          ["files/ssh_keys/rca.pub"],
        mysql_user: leihs,
        mysql_password: "r3yjqWkzYXjU.",
        mysql_database: "leihs_prod",
        mysql_host: "192.168.122.235",
        local_database: False,
        secret_token: fdb800e432b92b5421209ce179506b563e176d5ad6b309a3dd6c882c0563f60b206a4eeab26ada269ad3b7c5ca4d357611d387fe13a8572964123ea16cfe9d0a,
        logrotate_filename: "leihs2.local",
        test_instance: True
        }
    - { role: phusion-passenger-vhost,
        server_name: "leihs2.local" }
# An example of a demo instance which loads some demo data and reseeds it every night
- hosts: demo.leihs.local
  roles:
    - { role: leihs-instance,
        deploy_to: "/home/leihs/demo",
        version: "master",
        ruby_version: "2.1.5",
        user: leihs,
        authorized_for_deployment:
          ["files/ssh_keys/rca.pub"],
        mysql_user: leihs,
        mysql_password: "hNM8f7ej2sjjnlk02hd",
        mysql_database: "leihs_demo",
        secret_token: fdb800e432b9225421209ce174506b563e176d5ad6b309a3dd6c882c0563f60b206a4eeab26ada269ad3b7c5ca4d357611d387fe13a8572964123ea16cfe9d0a,
        logrotate_filename: "demo.leihs.local",
        demo_instance: True
        }
    - { role: phusion-passenger-vhost,
        server_name: "demo.leihs.local" }

# A production instance with cronjobs and everything
- hosts: leihs3.local
  roles:
    - { role: leihs-instance,
        deploy_to: "/home/leihs/production",
        version: "master",
        ruby_version: "2.1.5",
        user: leihs,
        authorized_for_deployment:
          ["files/ssh_keys/rca.pub"],
        mysql_user: leihs3,
        mysql_password: "wVy.atzKfvpqEwVy.atzKfvpqE",
        mysql_database: "leihs3_prod",
        secret_token: f8ad02524dce6757df486f07c4f7923dda19692441bbc31dade36c82d475bdb6ed60064e14f3d85f3ad837a7c85c63082fcfe47cd501da92ca14a4167842ad97,
        logrotate_filename: "leihs3.local"
        }
    - { role: phusion-passenger-vhost,
        server_name: "leihs3.local" }
