---
- hosts: leihs.local
  roles:
    - { role: leihs-instance,
        server_name: "leihs.local",
        deploy_to: "/home/leihs/test/current",
        version: "master",
        document_root: "/home/leihs/test/current/public",
        passenger_ruby: "/home/leihs/.rbenv/versions/2.1.5/bin/ruby",
        user: leihs,
        mysql_user: leihs,
        mysql_password: "hNM8f7ej2sjjnlk02hd",
        mysql_database: "leihs_prod",
        secret_token: fdb800e432b92b5421209ce179506b563e176d5ad6b309a3dd6c882c0563f60b206a4eeab26ada269ad3b7c5ca4d357611d387fe13a8572964123ea16cfe9d0a,
        rotate_logs: "/home/leihs/test/shared/log/*.log",
        test_instance: True
        }
